In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle as pkl

In [3]:
df = pd.read_csv("adult.data", sep=",")

In [12]:
df.sample(10)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
62,42,Private,116632,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States,>50K
24657,22,Private,175883,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
4891,23,Private,218215,Assoc-acdm,12,Never-married,Other-service,Own-child,White,Female,0,0,35,United-States,<=50K
15423,63,?,321403,9th,5,Separated,?,Not-in-family,Black,Male,0,0,40,United-States,<=50K
14063,61,Private,175999,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K
10219,31,Private,128591,9th,5,Divorced,Transport-moving,Not-in-family,White,Male,0,0,40,United-States,<=50K
29943,38,Federal-gov,207066,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,42,United-States,>50K
2266,32,Local-gov,286101,HS-grad,9,Never-married,Transport-moving,Unmarried,Black,Female,0,0,37,United-States,<=50K
5390,31,Private,101562,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,0,55,United-States,<=50K
17287,47,Private,145290,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,45,United-States,<=50K

In [8]:
columns=["age","workclass","fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","class"]

In [11]:
l=list(df.columns)
df.columns=columns
df.loc[len(df)]=l

In [13]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
class             0
dtype: int64

In [15]:
df.dtypes

age               object
workclass            str
fnlwgt            object
education            str
education-num     object
marital-status       str
occupation           str
relationship         str
race                 str
sex                  str
capital-gain      object
capital-loss      object
hours-per-week    object
native-country       str
class                str
dtype: object

In [21]:
df.shape

(32560, 15)

In [27]:
columns=df.columns
for i in columns:
    print(i,":",df[i].unique())

age : [50 38 53 28 37 49 52 31 42 30 23 32 40 34 25 43 54 35 59 56 19 39 20 45
 22 48 21 24 57 44 41 29 18 47 46 36 79 27 67 33 76 17 55 61 70 64 71 68
 66 51 58 26 60 90 75 65 77 62 63 80 72 74 69 73 81 78 88 82 83 84 85 86
 87]
workclass : <StringArray>
[' Self-emp-not-inc',          ' Private',        ' State-gov',
      ' Federal-gov',        ' Local-gov',                ' ?',
     ' Self-emp-inc',      ' Without-pay',     ' Never-worked']
Length: 9, dtype: str
fnlwgt : [83311 215646 234721 ... 34066 84661 257302]
education : <StringArray>
[   ' Bachelors',      ' HS-grad',         ' 11th',      ' Masters',
          ' 9th', ' Some-college',   ' Assoc-acdm',    ' Assoc-voc',
      ' 7th-8th',    ' Doctorate',  ' Prof-school',      ' 5th-6th',
         ' 10th',      ' 1st-4th',    ' Preschool',         ' 12th']
Length: 16, dtype: str
education-num : [13 9 7 14 5 10 12 11 4 16 15 3 6 2 1 8]
marital-status : <StringArray>
[   ' Married-civ-spouse',              ' Divorced', ' Married-spouse-absent',
         ' Never-married',             ' Separated',     ' Married-AF-spouse',
               ' Widowed']
Length: 7, dtype: str
occupation : <StringArray>
[  ' Exec-managerial', ' Handlers-cleaners',    ' Prof-specialty',
     ' Other-service',      ' Adm-clerical',             ' Sales',
      ' Craft-repair',  ' Transport-moving',   ' Farming-fishing',
 ' Machine-op-inspct',      ' Tech-support',                 ' ?',
   ' Protective-serv',      ' Armed-Forces',   ' Priv-house-serv']
Length: 15, dtype: str
relationship : <StringArray>
[       ' Husband',  ' Not-in-family',           ' Wife',      ' Own-child',
      ' Unmarried', ' Other-relative']
Length: 6, dtype: str
race : <StringArray>
[' White', ' Black', ' Asian-Pac-Islander', ' Amer-Indian-Eskimo', ' Other']
Length: 5, dtype: str
sex : <StringArray>
[' Male', ' Female']
Length: 2, dtype: str
capital-gain : [0 14084 5178 5013 2407 14344 15024 7688 34095 4064 4386 7298 1409 3674
 1055 3464 2050 2176 2174 594 20051 6849 4101 1111 8614 3411 2597 25236
 4650 9386 2463 3103 10605 2964 3325 2580 3471 4865 99999 6514 1471 2329
 2105 2885 25124 10520 2202 2961 27828 6767 2228 1506 13550 2635 5556 4787
 3781 3137 3818 3942 914 401 2829 2977 4934 2062 2354 5455 15020 1424 3273
 22040 4416 3908 10566 991 4931 1086 7430 6497 114 7896 2346 3418 3432
 2907 1151 2414 2290 15831 41310 4508 2538 3456 6418 1848 3887 5721 9562
 1455 2036 1831 11678 2936 2993 7443 6360 1797 1173 4687 6723 2009 6097
 2653 1639 18481 7978 2387 5060]
capital-loss : [0 2042 1408 1902 1573 1887 1719 1762 1564 2179 1816 1980 1977 1876 1340
 2206 1741 1485 2339 2415 1380 1721 2051 2377 1669 2352 1672 653 2392 1504
 2001 1590 1651 1628 1848 1740 2002 1579 2258 1602 419 2547 2174 2205 1726
 2444 1138 2238 625 213 1539 880 1668 1092 1594 3004 2231 1844 810 2824
 2559 2057 1974 974 2149 1825 1735 1258 2129 2603 2282 323 4356 2246 1617
 1648 2489 3770 1755 3683 2267 2080 2457 155 3900 2201 1944 2467 2163 2754
 2472 1411]
hours-per-week : [13 40 16 45 50 80 30 35 60 20 52 44 15 25 38 43 55 48 58 32 70 2 22 56 41
 28 36 24 46 42 12 65 1 10 34 75 98 33 54 8 6 64 19 18 72 5 9 47 37 21 26
 14 4 59 7 99 53 39 62 57 78 90 66 11 49 84 3 17 68 27 85 31 51 77 63 23
 87 88 73 89 97 94 29 96 67 82 86 91 81 76 92 61 74 95]
native-country : <StringArray>
[             ' United-States',                       ' Cuba',
                    ' Jamaica',                      ' India',
                          ' ?',                     ' Mexico',
                      ' South',                ' Puerto-Rico',
                   ' Honduras',                    ' England',
                     ' Canada',                    ' Germany',
                       ' Iran',                ' Philippines',
                      ' Italy',                     ' Poland',
                   ' Columbia',                   ' Cambodia',
                   ' Thailand',                    ' Ecuador',
                       ' Laos',                     ' Taiwan',
                      ' Haiti',                   ' Portugal',
         ' Dominican-Republic',                ' El-Salvador',
                     ' France',                  ' Guatemala',
                      ' China',                      ' Japan',
                 ' Yugoslavia',                       ' Peru',
 ' Outlying-US(Guam-USVI-etc)',                   ' Scotland',
            ' Trinadad&Tobago',                     ' Greece',
                  ' Nicaragua',                    ' Vietnam',
                       ' Hong',                    ' Ireland',
                    ' Hungary',         ' Holand-Netherlands']
Length: 42, dtype: str
class : <StringArray>
[' <=50K', ' >50K']
Length: 2, dtype: str
marital : [1 0]

In [22]:
df["marital"]=0

In [28]:
l=[' Married-civ-spouse',' Married-AF-spouse',]
df["marital"]=df["marital-status"].apply(lambda x: 1 if x in l else 0)
df.drop(["marital-status"],axis=1,inplace=True)

In [29]:
df.sample(10)

,age,workclass,fnlwgt,education,education-num,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class,marital
15479,27,Private,105598,HS-grad,9,Adm-clerical,Not-in-family,White,Male,0,0,40,United-States,<=50K,0
4432,52,State-gov,149650,Doctorate,16,Prof-specialty,Husband,White,Male,0,0,40,Iran,>50K,1
8488,24,Private,508548,HS-grad,9,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K,1
10849,35,Private,275522,7th-8th,4,Other-service,Unmarried,White,Female,0,0,80,United-States,<=50K,0
7649,43,Private,112607,11th,7,Sales,Husband,White,Male,0,0,60,United-States,<=50K,1
28475,71,?,116165,Some-college,10,?,Not-in-family,White,Female,0,0,14,Canada,<=50K,0
30060,33,?,393376,11th,7,?,Not-in-family,White,Female,0,0,40,United-States,<=50K,0
13344,33,Private,117779,HS-grad,9,Machine-op-inspct,Wife,White,Female,0,0,46,United-States,>50K,1
14230,20,Private,197752,Some-college,10,Adm-clerical,Own-child,White,Male,0,0,16,United-States,<=50K,0
19784,30,Private,158420,Bachelors,13,Machine-op-inspct,Not-in-family,White,Male,0,0,25,United-States,<=50K,0

In [31]:
columns=df.columns
for i in columns:
    print(i,":",df[i].unique())

age : [50 38 53 28 37 49 52 31 42 30 23 32 40 34 25 43 54 35 59 56 19 39 20 45
 22 48 21 24 57 44 41 29 18 47 46 36 79 27 67 33 76 17 55 61 70 64 71 68
 66 51 58 26 60 90 75 65 77 62 63 80 72 74 69 73 81 78 88 82 83 84 85 86
 87]
workclass : <StringArray>
[' Self-emp-not-inc',          ' Private',        ' State-gov',
      ' Federal-gov',        ' Local-gov',                ' ?',
     ' Self-emp-inc',      ' Without-pay',     ' Never-worked']
Length: 9, dtype: str
fnlwgt : [83311 215646 234721 ... 34066 84661 257302]
education : <StringArray>
[   ' Bachelors',      ' HS-grad',         ' 11th',      ' Masters',
          ' 9th', ' Some-college',   ' Assoc-acdm',    ' Assoc-voc',
      ' 7th-8th',    ' Doctorate',  ' Prof-school',      ' 5th-6th',
         ' 10th',      ' 1st-4th',    ' Preschool',         ' 12th']
Length: 16, dtype: str
education-num : [13 9 7 14 5 10 12 11 4 16 15 3 6 2 1 8]
occupation : <StringArray>
[  ' Exec-managerial', ' Handlers-cleaners',    ' Prof-specialty',
     ' Other-service',      ' Adm-clerical',             ' Sales',
      ' Craft-repair',  ' Transport-moving',   ' Farming-fishing',
 ' Machine-op-inspct',      ' Tech-support',                 ' ?',
   ' Protective-serv',      ' Armed-Forces',   ' Priv-house-serv']
Length: 15, dtype: str
relationship : <StringArray>
[       ' Husband',  ' Not-in-family',           ' Wife',      ' Own-child',
      ' Unmarried', ' Other-relative']
Length: 6, dtype: str
race : <StringArray>
[' White', ' Black', ' Asian-Pac-Islander', ' Amer-Indian-Eskimo', ' Other']
Length: 5, dtype: str
sex : <StringArray>
[' Male', ' Female']
Length: 2, dtype: str
capital-gain : [0 14084 5178 5013 2407 14344 15024 7688 34095 4064 4386 7298 1409 3674
 1055 3464 2050 2176 2174 594 20051 6849 4101 1111 8614 3411 2597 25236
 4650 9386 2463 3103 10605 2964 3325 2580 3471 4865 99999 6514 1471 2329
 2105 2885 25124 10520 2202 2961 27828 6767 2228 1506 13550 2635 5556 4787
 3781 3137 3818 3942 914 401 2829 2977 4934 2062 2354 5455 15020 1424 3273
 22040 4416 3908 10566 991 4931 1086 7430 6497 114 7896 2346 3418 3432
 2907 1151 2414 2290 15831 41310 4508 2538 3456 6418 1848 3887 5721 9562
 1455 2036 1831 11678 2936 2993 7443 6360 1797 1173 4687 6723 2009 6097
 2653 1639 18481 7978 2387 5060]
capital-loss : [0 2042 1408 1902 1573 1887 1719 1762 1564 2179 1816 1980 1977 1876 1340
 2206 1741 1485 2339 2415 1380 1721 2051 2377 1669 2352 1672 653 2392 1504
 2001 1590 1651 1628 1848 1740 2002 1579 2258 1602 419 2547 2174 2205 1726
 2444 1138 2238 625 213 1539 880 1668 1092 1594 3004 2231 1844 810 2824
 2559 2057 1974 974 2149 1825 1735 1258 2129 2603 2282 323 4356 2246 1617
 1648 2489 3770 1755 3683 2267 2080 2457 155 3900 2201 1944 2467 2163 2754
 2472 1411]
hours-per-week : [13 40 16 45 50 80 30 35 60 20 52 44 15 25 38 43 55 48 58 32 70 2 22 56 41
 28 36 24 46 42 12 65 1 10 34 75 98 33 54 8 6 64 19 18 72 5 9 47 37 21 26
 14 4 59 7 99 53 39 62 57 78 90 66 11 49 84 3 17 68 27 85 31 51 77 63 23
 87 88 73 89 97 94 29 96 67 82 86 91 81 76 92 61 74 95]
native-country : <StringArray>
[             ' United-States',                       ' Cuba',
                    ' Jamaica',                      ' India',
                          ' ?',                     ' Mexico',
                      ' South',                ' Puerto-Rico',
                   ' Honduras',                    ' England',
                     ' Canada',                    ' Germany',
                       ' Iran',                ' Philippines',
                      ' Italy',                     ' Poland',
                   ' Columbia',                   ' Cambodia',
                   ' Thailand',                    ' Ecuador',
                       ' Laos',                     ' Taiwan',
                      ' Haiti',                   ' Portugal',
         ' Dominican-Republic',                ' El-Salvador',
                     ' France',                  ' Guatemala',
                      ' China',                      ' Japan',
                 ' Yugoslavia',                       ' Peru',
 ' Outlying-US(Guam-USVI-etc)',                   ' Scotland',
            ' Trinadad&Tobago',                     ' Greece',
                  ' Nicaragua',                    ' Vietnam',
                       ' Hong',                    ' Ireland',
                    ' Hungary',         ' Holand-Netherlands']
Length: 42, dtype: str
class : <StringArray>
[' <=50K', ' >50K']
Length: 2, dtype: str
marital : [1 0]

In [37]:
df["workclass"].value_counts()

workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1297
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [ ]:
df.loc["?"][]="unknown"

C:\Users\HP\AppData\Local\Temp\ipykernel_21292\1678506346.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df["workclass"].loc[df["workclass"]=="?"]="unknown"

THE COLUMNS WORKCLASS AND RELATIONSHIP DON'T MATTER TO THE